---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
  - "{{ .Values.subdomain }}.{{ .Values.domain }}"
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-active ## 서비스명
        port:
          number: {{ .Values.port }}
